# Application Name
spring.application.name=StudentManagementSystem

# Server Port Configuration
server.port=7071

# MySQL Datasource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/studentmanagementsystem
spring.datasource.username=root
spring.datasource.password=190206

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true